apiVersion: apps/v1
kind: Deployment
metadata:
  name: kanban-deployment
  labels:
    app: kanban
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kanban
  template:
    metadata:
      labels:
        app: kanban
    spec:
      containers:
      - name: kanban
        image: thejas821/kanban:latest
        ports: 
        - containerPort: 80
